#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.296
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoListaDeTareas
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	public partial class BaseListasDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertLista(Lista instance);
    partial void UpdateLista(Lista instance);
    partial void DeleteLista(Lista instance);
    #endregion
		
		public BaseListasDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
	//	public BaseListasDataContext(System.Data.IDbConnection connection) : 
//				base(connection, mappingSource)
//		{
//			OnCreated();
//		}
		
		public BaseListasDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
//		public BaseListasDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
//				base(connection, mappingSource)
//		{
//			OnCreated();
//		}
		
		public System.Data.Linq.Table<Lista> Lista
		{
			get
			{
				return this.GetTable<Lista>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class Lista : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Tarea;
		
		private int _Hora;
		
		private int _Minuto;
		
		private int _Segundo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTareaChanging(string value);
    partial void OnTareaChanged();
    partial void OnHoraChanging(int value);
    partial void OnHoraChanged();
    partial void OnMinutoChanging(int value);
    partial void OnMinutoChanged();
    partial void OnSegundoChanging(int value);
    partial void OnSegundoChanged();
    #endregion
		
		public Lista()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarea", CanBeNull=false)]
		public string Tarea
		{
			get
			{
				return this._Tarea;
			}
			set
			{
				if ((this._Tarea != value))
				{
					this.OnTareaChanging(value);
					this.SendPropertyChanging();
					this._Tarea = value;
					this.SendPropertyChanged("Tarea");
					this.OnTareaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hora")]
		public int Hora
		{
			get
			{
				return this._Hora;
			}
			set
			{
				if ((this._Hora != value))
				{
					this.OnHoraChanging(value);
					this.SendPropertyChanging();
					this._Hora = value;
					this.SendPropertyChanged("Hora");
					this.OnHoraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Minuto")]
		public int Minuto
		{
			get
			{
				return this._Minuto;
			}
			set
			{
				if ((this._Minuto != value))
				{
					this.OnMinutoChanging(value);
					this.SendPropertyChanging();
					this._Minuto = value;
					this.SendPropertyChanged("Minuto");
					this.OnMinutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segundo")]
		public int Segundo
		{
			get
			{
				return this._Segundo;
			}
			set
			{
				if ((this._Segundo != value))
				{
					this.OnSegundoChanging(value);
					this.SendPropertyChanging();
					this._Segundo = value;
					this.SendPropertyChanged("Segundo");
					this.OnSegundoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
